### ISSUE TITLE
[API] Get one Gift : Unknown gift id

### ISSUE THREAD

**Issue by pchatard** [pchatard/giftlist#64]
Endpoint : `/lists/listId/gifts/giftId`
Method : `GET`

Right now, calling this with an unknown `giftId` (good format but not in our db) returns a 401, even if the giftId does not exists.

By curiosity, should we not return another code ?

**Comment by ndureiss** [comment]
I think it can be a good practice to return "Unauthorized" instead of a "Resource not found". In fact, in the case of a malveillant user which try to forge requests, he will not see the difference between existing giftId or non existing ones... Even if he has not access to both of them. 

What do you think @pchatard ?

**Comment by pchatard** [comment]
I'm ok with it. Let's keep it that way then. Thanks for the explanation!
